### ISSUE TITLE
AuthorizationService_UserHasPermission_Pass() does not pass

### ISSUE THREAD

**Issue by a-ridley** [CECS-491A/F5-broadwayBuilder#36]
#### Description
AuthorizationService_UserHasPermission_Pass() does not pass. All other tests do pass.

#### To Reproduce
To re-create what I did.
1. Delete database
2. Run all tests at the same time (database will be re-created during this step).
You should see that the test does not pass.

**Comment by zanderlx** [comment]
Issue has been resolved.
